### PR TITLE
Added a parameter to pass a title for coupon code

### PR DESCRIPTION
**Pull request by sbassah**
An update for the snippet to pass a field id to get a value that will be used to set the coupon name.

### CODE REVIEW

**Review by spivurno — CHANGES_REQUESTED** [review]
1. Does this work for WooCommerce as well?
2. What happens if field is specified or the field is empty? I would expect that it should default back to the coupon code.

**Review by sbassah — COMMENTED** [review]
Per your review, I've updated the snippet to first check if an ID was passed for the name field, if not the coupon code is used as the coupon name. Also, if a name field ID is passed, this update checks, if the name field is blank, and if it's blank it uses the coupon code as the coupon name.

With WooCommerce, the Post Title is the coupon code, so I assigned the coupon name to the Post content.

**Review by spivurno — APPROVED** [review]
Looks good! 

Approved but could you make one change before you merge? I think an inline comment explaining why we pass the coupon code as the post title and the coupon name is passed as the post content in the WC function would be helpful for understanding this in the future.

**Comment by spivurno** [comment]
Also, good work! 🤘

**Pull request merged**
