### PR TITLE
Added support to set the coupon limit using a field value

### PR DESCRIPTION
**Pull request by sbassah**
This PR adds support to set the coupon limit using a field value in addition to setting a static limit

### CODE REVIEW

**Review by sbassah — COMMENTED** [review]
No changes but just code formatting

**Review by spivurno — APPROVED** [review]
Excellent work, @sbassah! Approved. Is this your first PR with Gravity Wiz?

**Comment by spivurno** [comment]
PS - You can merge this whenever you're ready.

**Comment by sbassah** [comment]
Thanks a lot, David. 
This isn't my first PR with Gravity Wiz.  Some months ago I submitted a PR for a minor update for GP Read Only but this is the first time I didn't fork the Repo 😀.

**Pull request merged**
