### PR TITLE
added Instruction Video for populating current quarter of the year

### PR DESCRIPTION
**Pull request by dariospace**
I've created this videos since I wasn't sure how to use the snippet. I've found an HS thread with the reference to use it [HS#21817](https://secure.helpscout.net/conversation/1386182183/21817/)

### CODE REVIEW

**Comment by spivurno** [comment]
@dariospace Removed some extra lines from the snippet header here: https://github.com/gravitywiz/snippet-library/pull/231/commits/7ef702dd00db396db271302158cfa21d037f6607

Could you also capitalize "Video" in "Instruction video"?

**Comment by dariospace** [comment]
Sure, done!

**Review by scyt — CHANGES_REQUESTED** [review]
@dariospace Looks good. I think refreshing to reload the parameter can be a little confusing. It would probably be a good idea to keep the parameter in your clipboard so you can easily paste it in.

Could you redo this one without the refresh?

**Comment by dariospace** [comment]
@scyt I've made a new video!

**Review by scyt — APPROVED** [review]
Thanks for making that change. Looks great. ✅

**Pull request merged**
