### PR TITLE
Create gppa-add-a-custom-choice-template-to-choices.php

### PR DESCRIPTION
**Pull request by dariospace**
added hook

### CODE REVIEW

**Review by spivurno — APPROVED** [review]
✅

**Comment by dariospace** [comment]
@spivurno there's seem to be conflict when trying to merge this PR

**Comment by spivurno** [comment]
@dariospace Looks like there is already a snippet with this name. I combined the code from this PR with the existing solution as they are both part of the complete solution.

https://github.com/gravitywiz/snippet-library/blob/master/gp-populate-anything/gppa-add-a-custom-choice-template.php

**Comment by dariospace** [comment]
@spivurno ✅

**Pull request closed without merging**
