### PR TITLE
Added support for custom modifier values.

### PR DESCRIPTION
**Pull request by spivurno**
[HS#23585](https://secure.helpscout.net/conversation/1471850947/23585/)

Use the new `gwaft_modifier_value_CUSTOMVALUE` filter to replace your custom value with field IDs dynamically.

### CODE REVIEW

**Comment by spivurno** [comment]
@sbassah Could you review the code, test the new functionality on your end, and then get this on @scyt's plate to update the article with this new feature + usage example?

Might be worth creating a card for this in Notion like we're doing for new snippets and migrations. I'll let you and Scott decide on that. 🙂

**Comment by spivurno** [comment]
Worth noting that this supports passing multiple custom values.

```
{all_fields:exclude[myCustomList,myOtherList]}
```

**Comment by scyt** [comment]
> Might be worth creating a card for this in Notion like we're doing for new snippets and migrations. I'll let you and Scott decide on that. slightly_smiling_face

@sbassah Let's get a card made in Notion once you're done merging this.

**Review by sbassah — APPROVED** [review]
It works just as expected on my end. Perfect.

**Pull request merged**
