### PR TITLE
Add Support for Aggregate Functions

### PR DESCRIPTION
**Pull request by sbassah**
Original Snippet: https://snippi.com/s/ukdqjfw

### CODE REVIEW

**Review by spivurno — APPROVED** [review]
Made some formatting changes and fixed the issue where this wasn't working. 😂

**Comment by spivurno** [comment]
@sbassah Was there a card for this? No worries if not, just wanted to make sure I updated it if so.

**Comment by sbassah** [comment]
@spivurno Yes please, There is already a card for it your [Notion Review queue](https://www.notion.so/gravitywiz/70f5e5e598c74ca5ba4396c40cffdee8?v=4f031178324045aabaf4bfd2372b1ee9&p=79628dc215724961ba91bdedeeb42a47)

**Comment by sbassah** [comment]
@spivurno Awesome. I just tested it and works. You're a wizard🧙‍♂️😅.

I'll merge the PR, close the Ticket and update the Card in Notion.

**Pull request merged**
