### PR TITLE
Fixed issue where autocomplete was not disabled in Chrome.

### PR DESCRIPTION
**Pull request by spivurno**
Chrome seems to have changed their mind again about which autocomplete keywords they'll honor and ignore. Looks like "off" is working again.

### CODE REVIEW

**Comment by spivurno** [comment]
@scyt Could you see if this works for you? If so, I'm going to simplify the snippet again until we need the browser-specific complexity again (which I do not doubt we will 😝).

**Comment by scyt** [comment]
Not working for me with `autocomplete=off`.

**Comment by spivurno** [comment]
Strange. "password" is working again for me. I suspect that I'm hitting some weird edge case as I've seen this a few times but I can't recall the form I was working with the night I submitted this. I'm going to set this as a draft PR until I can recreate.

Thanks, @scyt!

**Comment by spivurno** [comment]
@scyt I think I figured this out. It's GPAA that's causing the conflict. It sets "off" for the autocomplete property. Not sure why changing it to "off" here fixes it for me but I'll dig back in "soon". 😅

**Comment by scyt** [comment]
@spivurno I just noticed this PR has been sitting in my review queue forever. For housekeeping purposes, I'm closing it.

**Comment by spivurno** [comment]
For posterity, @sbassah ended up encountering this again in a ticket and Clay fixed it in GPAA: https://secure.helpscout.net/conversation/1957113617/36964/#thread-5830344605

**Pull request closed without merging**
