### PR TITLE
Rounding by Increments Update

### PR DESCRIPTION
**Pull request by eihabi**
This PR imports the Rounding by Increments snippet and implements the following updates:

- Prevent rounding of floats if entered number is not greater than max
- Prevent rounding of floats if entered number is not less than min
- Adds support for rounding by decimal value
- Adds `gw-rounding-custom` filter to allow end-users to implement rounding algorithm of choice
- General PHPCS house-keeping

Additional info in HS.

### CODE REVIEW

**Comment by spivurno** [comment]
@eihabi Awesome work!

I love the idea for the custom filter. I think it'd be awesome to make it more generic/flexible. Rather than checking specifically for the "custom" string, we could pass any non-standard "modifier" through with a dynamic filter name.

```js
value = window.gform.applyFilters( 'gw_rounding_{0}'.format( action ), value, actionValue );
```

So the user might have a custom class like `gw-rounding-nearest9` and then bind to the dynamic `gw_rounding_nearest9` filter. This would allow the user to assign more meaning to their custom rounding class names and support multiple custom classes names without needing to know which field is being processed.

Thoughts?

**Review by spivurno — CHANGES_REQUESTED** [review]
Forgot to leave my previous comment as a review. Let me know what you think about the idea of a open-ended custom class powered by a dynamic filter.

**Comment by eihabi** [comment]
@spivurno Thanks and great idea! I've updated the filter to allow for arbitrary names.

**Review by spivurno — CHANGES_REQUESTED** [review]
A clever and clean implementation. Good work! 

One last thing... for security, we'll need to support this filter on the PHP side of things as well. See the `GW_Rounding::round()` method.

**Comment by eihabi** [comment]
@spivurno Done! Thanks for catching that, I overlooked the back-end on this one 😅

**Review by spivurno — APPROVED** [review]
Awesome work, my friend. 🌮

**Pull request merged**
