### PR TITLE
Close Comments when Post Created via Gravity Forms

### PR DESCRIPTION
**Pull request by dariospace**
Original Gist: https://gist.githubusercontent.com/spivurno/3710956

### CODE REVIEW

**Review by spivurno — CHANGES_REQUESTED** [review]
See the feedback on this one and implement here.

https://github.com/gravitywiz/snippet-library/pull/324#pullrequestreview-970804297

One other note on this one is we always use "123" for the form ID. More details on that here:

https://www.notion.so/gravitywiz/Snippet-Library-Code-Organization-Formatting-and-Naming-d5bee101d9674dfc98d7ec007867de2b#89a3c11b03474d63832a1618a55aee20

**Comment by dariospace** [comment]
@spivurno I've made the changes based on the Instruction Loom you shared

**Review by spivurno — APPROVED** [review]
Made a few more tweaks. Let me know how strict you'd like me to be when reviewing these. 😅

Video of the changes I made: https://www.loom.com/share/2d506981bca642c1a9036be63978ac61

**Comment by dariospace** [comment]
@spivurno you choose the level man! I'll comply as far as I'm capable of 🧙‍♂️, I won't be able (probably) to track the anonymous functions stuff (I've copy pasted the code form the old Gists 🙂)

**Pull request merged**
