### PR TITLE
Create gfcs-auto-select-only-choice.php.

### PR DESCRIPTION
**Pull request by guilamu**
## Context

⛑️ Ticket(s): https://secure.helpscout.net/conversation/2049282106/40053?folderId=14965

## Summary

The Gravity Forms Chained Selects field requires you to manually select a value in each Drop Down even if there is only a single option available in that Drop Down. This snippet will automatically selected an option when it is the only option available.

### CODE REVIEW

**Comment by spivurno** [comment]
@guilamu Thanks for the PR! It's our first guest submission for a brand new snippet so it'll be our guinea pig. Bear with us and all the conversation that is about to unfold. 😅

**Comment by spivurno** [comment]
@claygriffiths Doesn't look like our checks can run on external PRs. Any thoughts for the best way to get external PRs to align with our coding standards?

**Comment by guilamu** [comment]
Not sure if the question is addressed to me or not, I'm really a newbie to coding and even more to github. I can't really fix anything and I provide you this code written by a friend "as is". Feel free to modify it as you see fit or delete it if you think it's not worth it (I do really think this is fixing a massive bug of the Chained Select field GF won't fix though).

**Comment by spivurno** [comment]
@guilamu All good! Do you a good form export and CSV I can use to test this?

**Comment by spivurno** [comment]
Hey @guilamu, I've tweaked the snippet for clarity. Could you confirm that this is still working as expected for you?

**Comment by guilamu** [comment]
@spivurno Perfect, this is working as intended in all my forms. Thanks.

**Comment by spivurno** [comment]
Merged! Thanks @guilamu!

**Pull request merged**
