### PR TITLE
`gpecf-tax-inclusive-order-summary-markup.php`: Added a new snippet to display a tax inclusive order summary.

### PR DESCRIPTION
**Pull request by sbassah**
## Context

⛑️ Ticket(s): https://secure.helpscout.net/conversation/2172401409/45012?folderId=14964#thread-6474318188

## Summary

This snippet uses a custom tax item to display an order summary with tax-inclusive calculations, mostly preferred in EU countries. 

It adds support to applying the tax-inclusive order summary markup to all forms. 

https://www.loom.com/share/5806b1d635844acb8615ff885afabce6

### CODE REVIEW

**Comment by spivurno** [comment]
@sbassah So the product price includes the tax amount by default and then in the order summary, this adds a tax line item for the amount of tax that's been included? 

I see some logic in there that appears to be adjusting the product price. What's that about?

**Comment by sbassah** [comment]
@spivurno  Sorry, I am now seeing your comment. I didn't see the email notification. 

Yes, the product price includes the sales tax. The calculation adjusting the price deducts the Sale tax percentage from the product price to display the product price excluding the sale tax in the order summary. The total sales tax of all the products is displayed as a line item below the subtotal field.

**Comment by sbassah** [comment]
@spivurno Here's a video demo on how the snippet works.

https://www.loom.com/share/5806b1d635844acb8615ff885afabce6

**Review by spivurno — APPROVED** [review]
Love the initiative here, @sbassah! 

I'm a little concerned about the unit price, tax, and final total always aligning, particularly for "weirder" numbers but I'm happy to move forward with this and let customers report any strangeness they see. 

With that said, I think I'd be most comfortable moving this into the experimental folder until we've had more customers using it in real world scenarios.

**Comment by sbassah** [comment]
@spivurno Thanks, and well noted. I will work on moving it to the experimental folder.

**Pull request merged**
