### PR TITLE
Create gw-disable-submit-button-until-required-fields-are-field-out

### PR DESCRIPTION
**Pull request by sbassah**
Original Gist: https://gist.github.com/spivurno/1dc988d26c0bb3621a01

### CODE REVIEW

**Comment by scyt** [comment]
Looks good. A couple things to update:

- The filename and title in the comment are misspelled. Let's change the filename to `gw-disable-submit-button-until-required-fields-are-filled-out.php` and the comment title to match: 
  Gravity Wiz // Gravity Forms // Disable Submit Button Until Required Fields are Filled Out
- The filename is missing the extension. Add `.php` to the end.

**Comment by sbassah** [comment]
I've made the changes. Can you please check it out?

**Review by scyt — COMMENTED** [review]
The filename is now `w-disable-submit-button-until-required-fields-are-field-out.php`. Looks like the `g` at the front got dropped. 🙂

**Review by scyt — APPROVED** [review]

**Comment by sbassah** [comment]
@spivurno

**Pull request merged**
