### PR TITLE
Added new snippet: gw-update-posts.php

### PR DESCRIPTION
**Pull request by scyt**
This PR adds a new snippet that will update WP post titles and content with values from GF entry. Usage example:

```
new GW_Update_Posts( array(
	'form_id' => 123,
	'post_id' => 1,
	'title'   => 2,
	'content' => 3
) );
```

### CODE REVIEW

**Review by spivurno — APPROVED** [review]
Looks good!

**Review by spivurno — CHANGES_REQUESTED** [review]
Oops! Clay made a good point on security. We'll want to make sure the user has permission to edit the post before we update it. Otherwise, folks could override the field value with any post ID and update the content. 

**Edit:**
This is a good place to start.

```php
current_user_can( 'edit_post', $post->ID );
```

**Comment by scyt** [comment]
I added a simple bail if they don't pass a cap check after the post is retrieved. Do you think that's sufficient, or did you have something more in mind?

**Comment by spivurno** [comment]
That's perfect! 

Only other thing is a coding standard nitpick; comments should be sentenced cased.

✅

**Review by spivurno — APPROVED** [review]

**Pull request merged**
